name: soccer_app
description: "A new Flutter project."

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  kakao_flutter_sdk_user: ^1.9.3
  http: ^1.2.1
  provider: ^6.1.2
  url_launcher: ^6.0.20 # 추가
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  webview_flutter: ^2.0.12

flutter:
  assets:
    - assets/images/national/
    - assets/images/
    - assets/images/bundeseliga/
    - assets/images/kleague/
    - assets/images/laliga/
    - assets/images/premierleague/
